#!/usr/bin/env python3
"""
Find overlapping USDT trading pairs between KuCoin, MEXC, and Binance.
Outputs: pair counts, overlap analysis, and saves full list to data/kucoin_mexc_pairs.txt
"""
import ccxt
from pathlib import Path


def main():
    print("Loading exchange markets...")

    kucoin = ccxt.kucoin()
    mexc = ccxt.mexc()
    binance = ccxt.binance()

    kucoin.load_markets()
    mexc.load_markets()
    binance.load_markets()

    # Extract USDT spot pairs (active only)
    kc_usdt = {s for s in kucoin.markets if s.endswith("/USDT") and kucoin.markets[s].get("active", True)}
    mx_usdt = {s for s in mexc.markets if s.endswith("/USDT") and mexc.markets[s].get("active", True)}
    bn_usdt = {s for s in binance.markets if s.endswith("/USDT") and binance.markets[s].get("active", True)}

    print(f"\nUSDT pairs per exchange:")
    print(f"  KuCoin:  {len(kc_usdt)}")
    print(f"  MEXC:    {len(mx_usdt)}")
    print(f"  Binance: {len(bn_usdt)}")

    # Overlaps
    kc_mx = kc_usdt & mx_usdt
    kc_bn = kc_usdt & bn_usdt
    mx_bn = mx_usdt & bn_usdt
    all_three = kc_usdt & mx_usdt & bn_usdt

    # KuCoin+MEXC but NOT Binance = new opportunity surface
    kc_mx_not_bn = kc_mx - bn_usdt

    print(f"\nOverlap analysis:")
    print(f"  KuCoin ∩ MEXC:              {len(kc_mx)} (arb-able)")
    print(f"  KuCoin ∩ Binance:           {len(kc_bn)}")
    print(f"  MEXC ∩ Binance:             {len(mx_bn)} (existing arb)")
    print(f"  All three:                  {len(all_three)}")
    print(f"  KuCoin ∩ MEXC - Binance:    {len(kc_mx_not_bn)} (NEW opportunities)")

    # Save pair list
    output_dir = Path("data")
    output_dir.mkdir(exist_ok=True)
    output_file = output_dir / "kucoin_mexc_pairs.txt"

    with open(output_file, "w") as f:
        f.write(f"# KuCoin ∩ MEXC overlapping USDT pairs ({len(kc_mx)} total)\n")
        f.write(f"# Generated by find_kucoin_mexc_overlap.py\n\n")
        for pair in sorted(kc_mx):
            tag = " [also on Binance]" if pair in bn_usdt else " [KuCoin+MEXC ONLY]"
            f.write(f"{pair}{tag}\n")

    print(f"\nSaved to {output_file}")

    # Show some examples of KuCoin-only pairs
    if kc_mx_not_bn:
        print(f"\nSample KuCoin+MEXC only pairs (first 20):")
        for pair in sorted(kc_mx_not_bn)[:20]:
            print(f"  {pair}")


if __name__ == "__main__":
    main()
